version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - wget https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - unzip terraform_1.0.11_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo "Starting Terraform plan phase..."
      - terraform --version
  build:
    commands:
      - terraform init -input=false
      - terraform validate -input=false -out=tfplan
  post_build:
    commands:
      - echo "Completed Terraform validate phase"

# artifacts:
#   files:
#     - tfvalidate
#     - .terraform/**/*
#     - '**/*'
